### ISSUE TITLE
Beast options and resources in config

### ISSUE THREAD

**Issue by Wytamma** [mccoy-devs/mccoy#25]
Currently only the dynamic variables are passed to beast from the config. 

```
beast:  
  - "ePopSize=0.3"
  - "Date.dateFormat=Y"
  - "Date.delimiter=|"
  - "mutationRate=1.0"
  - "mcmc.threads=6"
  - "mcmc.chainLength=10000"
  - "treelog.logEvery=1000"
  - "tracelog.logEvery=1000"
```
However we should also pass the cli options and resources e.g.
```
beast:  
  beast:
     - "-beagle"
     - "-beagle_GPU"
  dynamic-variables:
      - "ePopSize=0.3"
      - "Date.dateFormat=Y"
      - "Date.delimiter=|"
      - "mutationRate=1.0"
      - "mcmc.threads=6"
      - "mcmc.chainLength=10000"
      - "treelog.logEvery=1000"
      - "tracelog.logEvery=1000"
   resources:     # Only used for submission to an HPC queue
    time: "20:00:00"
    mem: "4G"
    cpus: 1
```
